### PR TITLE
Export useful enums

### LINKED ISSUE #74: Expose event typings
Currently, the event typings are not exported from the `index.d.ts`, making it inaccessible for external libraries.

Could you consider exposing it? :) Accessing the event-related types would be very helpful.

### PR DESCRIPTION
**Pull request by marcospassos**
Fixes #74

### CODE REVIEW

**Comment by marcospassos** [comment]
@Yuyz0112 I'm not sure if the build failure is somehow related to the changes I made.

**Comment by Yuyz0112** [comment]
@marcospassos No, it was caused by a previous change.

**Comment by marcospassos** [comment]
@Yuyz0112 I forgot to build the typings, so it still inaccessible =/

**Comment by Yuyz0112** [comment]
@marcospassos have a try with `0.7.16`

**Comment by marcospassos** [comment]
It's perfect now! Thank you!

**Pull request merged**
