### PR TITLE
Fix for test cases mentioned in #1379

### LINKED ISSUE #1379: [Bug]: addHoverClass creating invalid css
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb-snapshot

### Version

2.0.0-alpha.11

### Expected Behavior

Styling should work

### Actual Behavior

Replay is crashing due to stylesheet becoming invalid on replay from the addHoverClass function

### Steps to Reproduce

Is you have a selector like 
```
[_nghost-ng-c4172599085]:not(.fit-content).aim-select:hover:not(:disabled, [_nghost-ng-c4172599085]:not(.fit-content).aim-select--disabled, [_nghost-ng-c4172599085]:not(.fit-content).aim-select--invalid, [_nghost-ng-c4172599085]:not(.fit-content).aim-select--active) { border-color: rgb(84, 84, 84); }
``` 

then it will be replaced in the `addHoverClass` by

``` 
[_nghost-ng-c4172599085]:not(.fit-content).aim-select:hover:not(:disabled, [_nghost-ng-c4172599085]:not(.fit-content).aim-select.\:hover:not(:disabled, [_nghost-ng-c4172599085]:not(.fit-content).aim-select--disabled, [_nghost-ng-c4172599085]:not(.fit-content).aim-select--invalid, [_nghost-ng-c4172599085]:not(.fit-content).aim-select--active) {
        border-color: rgb(84, 84, 84);
    }
```

Which is invalid css.

It looks to be something to do with the logic in the parsing, where the selectors looks like

```[_nghost-ng-c4172599085]:not(.fit-content).aim-select:hover:not(:disabled```

Which is then getting fed into the addHoverClass function

### Testcase Gist URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dengelke**
Update of parsing function using selector from [here](https://github.com/NxtChg/pieces/blob/master/js/css_parser/css_parse.js) and update to logic for `,` inside `()` and associated tests to fix #1379

### CODE REVIEW

**Comment by jaj1014** [comment]
got around to testing this against the test recording I created that has the `{}` in the attribute value of the selectors and it seems to be working! It plays back w/ all the correct hovering and such.

thanks @dengelke ! - hopefully this can get into the queue for reviewing the solution 🤞

**Comment by Juice10** [comment]
@dengelke can you add a changeset (see other comment above) and add the link of where you found the css parser to the code so we can keep track of where this came from if it ever needs updating?

**Comment by dengelke** [comment]
@Juice10 updated the changeset and added a comment in the code

**Review by Juice10 — APPROVED** [review]

**Comment by eoghanmurray** [comment]
@dengelke would you be able to take a quick look at #1440 which covered the same ground.  I've merged the remainder of it last night into trunk; the remaining case was to do with handling single/double quotes (attr selectors).

**Pull request merged**
