### PR TITLE
Tests: Iframe event order

### PR DESCRIPTION
**Pull request by Juice10**
Adds tests ~and fixes~ _for_ https://github.com/rrweb-io/rrweb/issues/567

_These tests will pass once the changes are accepted in https://github.com/rrweb-io/rrweb-snapshot/pull/78 and a new version of rrweb-snapshot is added in package.json_

### CODE REVIEW

**Comment by Juice10** [comment]
I'm not sure if using `setTimeout` is the right approach here. It works but if we could do it without `setTimeout` I would prefer that.

@eoghanmurray do you think it would be possible to use the MutationBuffers to keep these mutations from getting added until the FullSnapshot has been built?

**Comment by Yuyz0112** [comment]
Hi @Juice10, thanks for the PR.

I think https://github.com/rrweb-io/rrweb-snapshot/pull/78 is a better approach.

But I'm curious because I think I already handle the order issue with this [queue](https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L1138). Are you experiencing any issues in the replay?

**Comment by Juice10** [comment]
> Hi @Juice10, thanks for the PR.
My pleasure!
> I think [rrweb-io/rrweb-snapshot#78](https://github.com/rrweb-io/rrweb-snapshot/pull/78) is a better approach.
I totally agree, I combed through the snapshot output and PR 78 seems consistent and in the correct order.
> But I'm curious because I think I already handle the order issue with this [queue](https://github.com/rrweb-io/rrweb/blob/master/src/replay/index.ts#L1138). Are you experiencing any issues in the replay?
Yes, the new document queue only works if the parentId’s id is not in use and the parent can’t be found, I my case I tend to come across a lot of ids that are reused so the parent is found and the new document queue isn’t triggered.

**Comment by eoghanmurray** [comment]
> @eoghanmurray do you think it would be possible to use the MutationBuffers to keep these mutations from getting added until the FullSnapshot has been built?

Maybe! (I've only recently had a chance to glance at the changes that resulted in a mutationbuffer per iframe)

**Comment by Yuyz0112** [comment]
@Juice10 I've published rrweb-snapshot v1.1.4

**Comment by Yuyz0112** [comment]
looks like CI is failing https://travis-ci.com/github/rrweb-io/rrweb/builds/228652215

**Comment by Juice10** [comment]
There seem to be some inconsistencies between my development environment and CI. Solved most of them by upgrading puppeteer. I ran out of time yesterday but I'll try to fix the last one today.

**Comment by Juice10** [comment]
@Yuyz0112 looks like this PR is good to go now!

**Pull request merged**
