### PR TITLE
fix: add mutation lost in slimDOMOptions

### PR DESCRIPTION
**Pull request by wfk007**
fix: https://github.com/rrweb-io/rrweb/issues/993

### CODE REVIEW

**Comment by wfk007** [comment]
in rrweb@2.0.0-alpha.1, mirror.getId() return -1 may caused by:

1. mutation add: child node may be pushed before its newly added parent, rrweb uses a DoubleLinkedList to store these nodes
2. slimDOMOptions: true, and the Node is an `IGNORED_NODE`, **but not in Mirror**

considering case 2:
in rrweb@1.1.3, we can use `node.__sn` to check whether nextSibling is an `IGNORED_NODE`
**BUT** in in rrweb@2.0.0-alpha.1, we can not
because the information with `IGNORED_NODE` neither in `node.__sn` nor in `Mirror`

**Comment by wfk007** [comment]
before:

https://user-images.githubusercontent.com/22289445/189289797-2b36b3d1-fd54-4139-80d2-a80592945564.mov

after fixed:

https://user-images.githubusercontent.com/22289445/189290282-d14ae704-1ff8-47ed-aa8b-4178ea5654d0.mov

**Review by Mark-Fenng — APPROVED** [review]
Thanks for your very nice pull request. The description and solution are very clear and clean.

The failure of Format Check CI can be ignored because it may be caused by the old branch base. I've checked the snapshot.ts and there's no formatting issue.

**Comment by wfk007** [comment]
@Mark-Fenng @Yuyz0112
Hi, is this pending any other changes?

**Comment by Mark-Fenng** [comment]
Nope, I think everything is good. Just waiting for @Yuyz0112's review.

**Comment by Yuyz0112** [comment]
sorry for the late

**Pull request merged**
