### PR TITLE
Deduplicate config for BROWSER_ONLY

### PR DESCRIPTION
**Pull request by eoghanmurray**
A little bit of de-duplication so that the BROWSER_ONLY config isn't specified twice.
Also intend to add another command to filter the output to just iife targets, so checking if this approach is a good idea.

### CODE REVIEW

**Comment by Yuyz0112** [comment]
I'm not sure that making the rollup config file more 'dynamic' is better for maintaining and understanding.

But I'm still open to the change of it if there are some stronger reasons.

**Comment by eoghanmurray** [comment]
Me breaking it up helped me understand what the config was doing. The deduplication in particular helped me clarify that the BROWSER_ONLY was just a subset of the main build (and how it was).
My building needs are embodied by `browser-unpacked`, I'm hoping that this approach makes it easier for others to create similar configs.  I'm not fully happy with the naming though ('browser', 'suppress', 'only')

**Comment by Yuyz0112** [comment]
@eoghanmurray Would you mind to check the latest master branch's rollup config? I think it may be a better base to extend these functionalities.

**Comment by eoghanmurray** [comment]
I've reapplied the changes on top of the current master.
I appreciate my changes may not be easy to understand here with the added special keywords 'suppress' and 'only'.

> Would you mind to check the latest master branch's rollup config? I think it may be a better base to extend these functionalities.

I really don't understand all the different configs or what they are for.
Please go ahead and close this pull request if it is not providing any benefit!

**Comment by eoghanmurray** [comment]
Close as I've abandoned attempts to keep this up to date w.r.t. master and did a custom hack instead to prevent compilation of non `iife` targets.

**Pull request closed without merging**
