### PR TITLE
Impl record iframe

### PR DESCRIPTION
**Pull request by Yuyz0112**

### CODE REVIEW

**Comment by dcaravana** [comment]
@Yuyz0112 any chance this is going to be done shortly?

Or better, any idea when this could be done?

Thanks!

**Comment by Jupiter-sxc** [comment]
使用了iframe的内容是有了，但是回放时鼠标移动到iframe的位置，就消失了，回放的时候iframe也没有按录制的滚动，请问大概是哪里出了问题呢

**Comment by dcaravana** [comment]
Gentle bump.

**Comment by Yuyz0112** [comment]
things go to https://github.com/rrweb-io/rrweb/pull/481

**Pull request closed without merging**
