### PR TITLE
chore: export canvasMutation

### PR DESCRIPTION
**Pull request by daibhin**
We are trying to support canvas playback without needing to remove the iframe sandbox (by enabling the `UNSAFE_replayCanvas` flag). Exposing this method would really help

### CODE REVIEW

**Comment by Juice10** [comment]
This is very cool Daibhin, the rrweb team is really keen on adopting the whole solution to be pulled in for everyone to use. Would you be open to contributing the whole solution (as a plugin perhaps, or as part of regular rrweb)? I'd can personally lend a hand and make sure it lands in master.

**Comment by benjackwhite** [comment]
> This is very cool Daibhin, the rrweb team is really keen on adopting the whole solution to be pulled in for everyone to use. Would you be open to contributing the whole solution (as a plugin perhaps, or as part of regular rrweb)? I'd can personally lend a hand and make sure it lands in master.

This is 100% our intention. Main issue is we want to test this with a range of use cases first and we're blocked on that due to the missing export :D

Could we get this in first otherwise we will be stuck in a chicken-egg place 😉

**Comment by daibhin** [comment]
Hi @Juice10. Sorry for the slow reply here, I'm just coming back from vacation. As @benjackwhite mentioned, would love to get this in first to properly test that everything works end to end locally before submitting a PR for a plugin.

One of the tests is failing with what seems to be an unrelated timeout. I don't seem to be able to rerun it. If we could get this in soon I'm hoping to spend the end of this week getting everything production ready.

**Comment by Juice10** [comment]
@daibhin yes master branch is broken currently but that'll be fixed soon so feel free to ignore it. Could you add a changeset, then I can merge this one

**Comment by daibhin** [comment]
@Juice10 done. It's my first time working with changesets so let me know if I've done things correctly :)

**Review by Juice10 — APPROVED** [review]

**Comment by Juice10** [comment]
@daibhin You did it perfectly, merged! Thanks for the contribution, really looking forward to seeing the results of what you are working on.

**Pull request merged**
