### PR TITLE
fix: Fix CSS rules captured in Safari

### PR DESCRIPTION
**Pull request by mydea**
Safari does not capture some css selectors correctly, so we need to fix them, or else playback fails for them.

Closes https://github.com/rrweb-io/rrweb/issues/1208

ref https://github.com/getsentry/rrweb/pull/86

### CODE REVIEW

**Review by Juice10 — APPROVED** [review]

**Comment by Juice10** [comment]
@mydea thanks for submitting this, could you add a Changeset then I can merge this issue

**Comment by mydea** [comment]
> @mydea thanks for submitting this, could you add a Changeset then I can merge this issue?

Added a changeset 👍

**Comment by eoghanmurray** [comment]
In light of performance efforts in #1271 I wonder whether it's desirable to run a browser check before employing the `validateStringifiedCssRule` function?

I believe (correct me if I'm wrong) that the `if (cssStringified.includes(':')) {` check will succeed for nearly 100% of css strings, so the regex will be needlessly run in non-safari browsers.  Is that correct?

**Comment by eoghanmurray** [comment]
@mydea I've done a slight rewrite of the test in #1280
if you have a chance, could you validate that that still does the right thing in Safari?

**Comment by JonasBa** [comment]
> In light of performance efforts in #1271 I wonder whether it's desirable to run a browser check before employing the `validateStringifiedCssRule` function?
> 
> I believe (correct me if I'm wrong) that the `if (cssStringified.includes(':')) {` check will succeed for nearly 100% of css strings, so the regex will be needlessly run in non-safari browsers. Is that correct?

Correct, + regexp.replace will always allocate a new string for you, so you are also performing an unnecessary copy

**Pull request merged**
