### PR TITLE
devicePixelRatio should be useful 

### PR DESCRIPTION
**Pull request by eoghanmurray**
e.g. during replay to determine how to scale things like mouse pointers (or drag circles)

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Do you have any idea how to use this during replay?

**Comment by eoghanmurray** [comment]
Ya I guess I'm working on some things to have a proper 'touch' indicator in the replayer for mobile devices, rather than the desktop style pointer cursor... in that context, I believe the devicePixelRatio will be useful for sizing the touch circle correctly, however I haven't put this into practice yet.

I'll put this all together in a new PR.

**Comment by eoghanmurray** [comment]
Close this one until I can show it's use in the replayer :+1:

**Comment by eoghanmurray** [comment]
I don't think this is actually necessary;
I've estimated the touch circle as 70px in https://github.com/rrweb-io/rrweb/pull/662
and I don't think devicePixelRatio has a bearing on this.

**Pull request closed without merging**
