### PR TITLE
Refactor to preclude the need for a continuous raf loop

### PR DESCRIPTION
**Pull request by eoghanmurray**
It seems to me that the raf loop is unnecessary, so I've removed it to get your feedback.

Instead we queue up a single raf callback which will clear anything added in this frame.

I've no understanding as to why this exclusivity is per animation frame, and not (say) per emitted mutation event, any insight into that?

### CODE REVIEW

**Comment by eoghanmurray** [comment]
Oh yeah; these changes haven't been tested!

**Comment by eoghanmurray** [comment]
Although I have it in production, so it's not obviously breaking things, there could be some subtleties with the shadowbuffer that might need expert analysis or a test...

I wrote this based on the logic of how the weak map was cleared etc.

**Comment by JonasBa** [comment]
@eoghanmurray very welcome change! This was creating a lot of noise when profiling the code 👏🏼

**Comment by eoghanmurray** [comment]
@JonasBa this is a hard one for anyone to review and we don't have tests on it.
Are you running this in production by any chance?

**Review by Juice10 — APPROVED** [review]

**Pull request merged**
