### PR TITLE
slimDOM - omit from mutations

### PR DESCRIPTION
**Pull request by eoghanmurray**
See https://github.com/rrweb-io/rrweb-snapshot/pull/36
for when this should be accepted

### CODE REVIEW

**Comment by eoghanmurray** [comment]
@Yuyz0112 a review of how this handles mutations would be appreciated ...
In the context of f7845818fc2b8877845229ef9475b9c02dd061b9
is there a similar change I'd need to do to keep the doubly linked list working okay, i.e. skip over those new `{id: -2}` nodes?

**Comment by eoghanmurray** [comment]
@Yuyz0112 I think there needs to be a new release of rrweb-snapshot to get the checks to pass.

I mentioned elsewhere about merging the 2 projects....
- are there any known users of rrweb-snapshot, or is it aspirational that someone will use it independently of this repository?
- could the node module for rrweb-snapshot be generated as a separate output from a single merged repository?
Just a thought!

**Comment by Yuyz0112** [comment]
Hi @eoghanmurray 

Since I've released rrweb-snapshot@1.0 with some breaking changes in API, I manually pick the commits in this PR to https://github.com/rrweb-io/rrweb/commit/3d5f2e2719cdfa9a670b19b5a81906e8c3066c1c to resolve the conflicts.

**Comment by Yuyz0112** [comment]
@eoghanmurray Could this be closed?

**Comment by eoghanmurray** [comment]
@Yuyz0112 I've rebased upon this version now in our codebase so I'll let you know if any problems arise from it

**Pull request closed without merging**
