### PR TITLE
Try add configurable threshold for events throttling

### PR DESCRIPTION
**Pull request by mpstv**
Tried to make an improvement #54. Prease review my code.

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Hi @mpstv, thanks for the PR!

I think you can follow the implementation of other configurations in the recorder, such as the `blockClass`.

The steps to add a configuration can be:
1. add it to the record options(https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L28), and set a default value if needed(https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L33)
2. add it to the observer params(https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L180)
3. pass it to the specific observer(https://github.com/rrweb-io/rrweb/blob/master/src/record/index.ts#L180). In your case, it could be the second param of `initMoveObserver`.
4. use it in the specific observer.

**Comment by mpstv** [comment]
Hi @Yuyz0112, thanks for fast feedback.
I changed my commit in according your recommendation. (I hope got it right).
Waiting for review my fixes.

**Comment by Yuyz0112** [comment]
LGTM, going to merge this PR. Thanks for your contribution! @mpstv 

BTW, I think I would like to think a bit more about the configuration interface before publishing a new version.

For example, I may introduce a more general configuration like `sampling` and the interface may look like
```
{
  sampling: {
    mousemove: 50,
    scroll: 100,
    ...
  }
}
```

**Comment by alexwenbj** [comment]
> LGTM, going to merge this PR. Thanks for your contribution! @mpstv
> 
> BTW, I think I would like to think a bit more about the configuration interface before publishing a new version.
> 
> For example, I may introduce a more general configuration like `sampling` and the interface may look like
> 
> ```
> {
>   sampling: {
>     mousemove: 50,
>     scroll: 100,
>     ...
>   }
> }
> ```

It is a nice proposal! I don't know are these features add to it?Moreover, is it possible to add some other configures to it?For example,I just want to record the actions inside an element, and ignore all the others,by now,I must configure all the ignore element classes.

**Comment by Yuyz0112** [comment]
@alexwenbj https://github.com/rrweb-io/rrweb/issues/111 discuss record on a specific element.

Would you like to open an issue about sampling config for tracking?

**Pull request merged**
