### PR TITLE
Fix: Switch to real dom before rebuilding fullsnapshot

### PR DESCRIPTION
**Pull request by YunFeng0817**
This pull request makes rrdom optimization robust.

1. Normally rebuilding full snapshots should not be under a virtual dom environment.
But if the order of data events has some issues, it might be possible.
Adding a check to avoid any potential issues.

2. Fix the bug: If an RRNode appends the same child twice, the child nodes will become an infinite linked list. This is a bug imported in #1127

### CODE REVIEW

**Comment by Juice10** [comment]
By setting usingVirtualDom to false, aren’t you essentially turning off all rrdom/virtual dom optimizations whenever you hit a full snapshot?

**Comment by YunFeng0817** [comment]
> By setting usingVirtualDom to false, aren’t you essentially turning off all rrdom/virtual dom optimizations whenever you hit a full snapshot?

Yes, because if a new fullsnapshot is rebuilt, the status of the existing virtual dom doesn't mean anything as it represents the previous snapshot. `usingVirtualDom` is an internal switch that determines the current dom environment.  It's different from the replayer's configuration `useVirtualDOm`.

**Comment by eoghanmurray** [comment]
For future work: I feel like the `usingVirtualDom` global is dangerous; I'd prefer that this variable be passed down the call chain to each function rather than relying on global state.  I've come across a situation in last few weeks where after an error, more errors were generated because it's state wasn't reset.

**Comment by YunFeng0817** [comment]
Your suggestion can also help. I think if this pull request is merged, there are not many serious bugs left.

**Review by Juice10 — APPROVED** [review]

**Pull request merged**
