### PR TITLE
start to support live mode

### PR DESCRIPTION
**Pull request by Yuyz0112**
1. add a liveMode flag to config, when liveMode is set, the timer
will keep running even though all the actions casted
2. add a public method addEvent, which will cast newly added event
in sync
3. move mouse in sync mode with the latest position info

### CODE REVIEW

**Comment by Yuyz0112** [comment]
related to #45

**Comment by eoghanmurray** [comment]
Is this missing an `events.push`?  e.g. `getMetaData().totalTime` reports the wrong time after events have been added;

```        Replayer.prototype.addEvent = function (event) {
            this.events.push(event);
            var castFn = this.getCastFn(event, true);
            castFn();
        };
```

**Comment by rifaideen** [comment]
@Yuyz0112 - First of all, this is great tool. Can you please share the example on iveMode?

```js
    new Player({
      target: document.getElementById('preview'),
      data: {
        events: recordings,
        autoPlay: true,
      },
      liveMode: true,
    })
```
I'm trying to broadcast live event but not sure where I'm wrong.

**Comment by eoghanmurray** [comment]
The `liveMode` is more of an internal flag to keep the playback loop running ... it could probably be removed if the playback loop could be restarted upon subsequent call to `addEvent`.

We got the live/cobrowsing functionality working ok by feeding the output of `emit` to `addEvent` — it wasn't working for us prior to the #191 change we did so I imagine there's not many using it yet.

If you wish to record in one browser and do live playback on a remote browser you likely are going to want to feed the events through a websocket server on both ends.  That'd be out of scope of this project as it's only one of many possible use cases, and there are many ways of implementing it.

**Comment by rifaideen** [comment]
@eoghanmurray - Thank you. I have already figured out and it works well but I see the lagging in mouse pointer movements, while broadcasting the live session.

**Comment by nikhilrayaprolu** [comment]
@rifaideen any example code on how you could implement cobrowsing?

**Comment by rifaideen** [comment]
@nikhilrayaprolu - It should be something like this:

```js
import { Replayer, unpack } from 'rrweb';

let recordings = [];

let player = null;

function livePlay(data) {
  if (player === null && recordings.length >= 2) {
    player = new Replayer(recordings, {
      liveMode: true,
      root: document.getElementById('preview'),
      unpackFn: unpack,
    });
    player.play();
  } else if (recordings.length < 2) {
    recordings.push(JSON.parse(data));
  }

  if (player !== null) {
    player.addEvent(JSON.parse(data));
  }
});

// receive live events from the target page or element and call the below function
livePlay(data);
```

**Comment by Yuyz0112** [comment]
Hi @nikhilrayaprolu @rifaideen 

I suggest you check my new PR https://github.com/rrweb-io/rrweb/pull/226 which refactoring the live mode with a more solid and easy to use API.

**Comment by rifaideen** [comment]
@Yuyz0112 - Actually I was experiencing the lag in replay especially the mouse move events and hopefully this [#226](https://github.com/rrweb-io/rrweb/pull/226) would resolve this issue I think.

**Comment by Yuyz0112** [comment]
@rifaideen Yes, the lag is one of the issues being solved.

**Comment by rifaideen** [comment]
@Yuyz0112 - One more thing which is not related to rrweb, however, it's all about webpage heatmaps. do you have any sample implementations?

**Comment by Yuyz0112** [comment]
@rifaideen Not yet. I do not have too much sense about how to implement a heatmap on the events.

**Comment by rifaideen** [comment]
@Yuyz0112 - okay and one more question. what are the events supported by `rrweb-player`. I have tried to add event handler for `IncrementalSnapshot` event in the `replayer.addEventListener` method but it was not successful.

**Comment by nikhilrayaprolu** [comment]
@rifaideen  it looks like the code sample you provided is an example for a live view but in case of co-browsing, the events are sent in a bidirectional manner. So is there a way to send mouse movements from the second screen to the first screen and first screen to the second screen?

**Pull request merged**
