### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by MagnusDot**
Update for working in google chrome

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Hi @MagnusDot , the replay iframe sandbox was designed to be not allowed scripts. Is there any case your replayer is not working?

**Comment by MagnusDot** [comment]
In all the case the replay player don't want to be opened without "allow-scripts"

**Comment by Yuyz0112** [comment]
Okay, so you mean the replayer is not replaying correctly or you are just seeing some errors like:
```
Blocked autofocusing on a form control because the form's frame is sandboxed and the 'allow-scripts' permission is not set.
```

**Comment by MagnusDot** [comment]
my error was exactly : 
`document's frame is sandboxed and the 'allow-scripts' permission is not set. rrweb`

**Comment by MagnusDot** [comment]
> my error was exactly :
> `document's frame is sandboxed and the 'allow-scripts' permission is not set. rrweb`

and with editing the sandbox options the problem passed away

**Comment by Yuyz0112** [comment]
This was designed to work like this(except the error was not muted).

Further reading: https://github.com/rrweb-io/rrweb/blob/master/docs/sandbox.md#iframe-sandbox.

**Comment by MagnusDot** [comment]
I can udersta,t it's a problem of security but if "allow-script" is not activateur that call the error  and stop all the program

**Comment by Yuyz0112** [comment]
Could you provide which website are you trying to record or provide some recorded events to me for debugging?

**Comment by MagnusDot** [comment]
I'm trying to work on a local project i can give you the recorded event 
https://pastebin.com/MGR6mrKR

**Comment by Yuyz0112** [comment]
[debug-2019-04-12_09.57.07.zip](https://github.com/rrweb-io/rrweb/files/3071262/debug-2019-04-12_09.57.07.zip)
I have replayed it and record a video, it looks like working correctly.

**Comment by MagnusDot** [comment]
Did you use the Chrome one, thie is where the problem is

**Comment by Yuyz0112** [comment]
Yes, I'm using chrome.
Could you provide your replayer code for debugging?

**Comment by MagnusDot** [comment]
Yes i'm going to work and send it to you ^^

**Comment by MagnusDot** [comment]
`
<script>
    function replay() {

        if (ontime == 0) {
            ontime = 1;
            const events = <?php echo file_get_contents('public/js/data.json'); ?>;


            new rrwebPlayer({
                target: document.getElementById("video"), // customizable root element
                data: {
                    events,
                    autoPlay: true,
                },
            });

        }


    }
</script>`

**Comment by Yuyz0112** [comment]
Sorry, still could not reproduce your issue.

**Comment by MagnusDot** [comment]
> Sorry, still could not reproduce your issue.

ha, si refuse my pull it's maybe my config, i've done some change it's working now for me ^^ 👍 thx for you're time =)

**Pull request closed without merging**
