### PR TITLE
Fix for trying to get the __sn value of a null node

### PR DESCRIPTION
**Pull request by IMFIL**
fix for: https://github.com/rrweb-io/rrweb/issues/98

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Hi @IMFIL Are you using the `checkout` feature when facing this problem?

**Comment by IMFIL** [comment]
I was not using checkout when faced with this issue !

**Comment by jlalmes** [comment]
Could we consider closing this PR and merging https://github.com/rrweb-io/rrweb/pull/572 ?

**Comment by arpowers** [comment]
@Yuyz0112 running into this also, problems are happening on Safari browsers. 

in this [minified source](https://s.darwin.to/6021bb51cab5e867e188c0e4.js) the following code: 
```js
getId(y.value.parentNode)
```

is throwing "TypeError: null is not an object (evaluating 'y.value')"  which is attributable to RRWeb.

**Comment by Yuyz0112** [comment]
@arpowers Could you try v1.0.0-beta.0 to see whether the issue still exist?

**Comment by arpowers** [comment]
@Yuyz0112 sure, is it safe to use in production or just run it locally?

**Pull request closed without merging**
