### PR TITLE
Ensure animations don't continue playing when we've paused playback

### PR DESCRIPTION
**Pull request by eoghanmurray**
Further work:
The animation state won't follow scrubbing/jumping of playback position, but I don't know any way of achieving that.

### CODE REVIEW

**Comment by Yuyz0112** [comment]
LGTM.

And I think this is a try-my-best strategy right @eoghanmurray ? Because there may be some JS animation we could not pause. And basically we are out of control with the animation state.

**Comment by eoghanmurray** [comment]
Yes, it's just handles the a specific CSS animation that I noticed in a recording.

Any JS animations should be paused naturally as they are being rendered via mutations though right?  
Maybe you are thinking of GIF animations?  
If so ya that would be under 'further work' :relaxed:  e.g. via https://github.com/ctrl-freaks/freezeframe.js (which has a typescript implementation)

**Comment by Yuyz0112** [comment]
Thanks!

**Comment by Mark-Fenng** [comment]
@eoghanmurray In my application, I need the CSS transition finished after I paused play. Could we add an option for this?

**Pull request merged**
