### PR TITLE
Move mutation processing into it's own class

### PR DESCRIPTION
**Pull request by eoghanmurray**
This should stand on it's own as a refactor, but is intended as a basis
for exposing the new MutationBuffer object to further outside control e.g.
to 'mute' or batch up mutation emission when the page becomes inactive
from a https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
point of view

### CODE REVIEW

**Comment by eoghanmurray** [comment]
Not currently working; output is producing this:
```
MutationBuffer.prototype.processMutations = function (mutations) {
   ...
   var _this = this;
   mutations.forEach(this.processMutation);
```
instead of 
```
mutations.forEach(_this.processMutation);
```

**Comment by eoghanmurray** [comment]
Ok, working now with the 05334ef152b365458d08e0376592031bdbb67661 commit.

**Comment by eoghanmurray** [comment]
Have solved the bind problem by making all methods use the Arrow function expressions.
Let me know if there's a neater way of doing methods (with the ability to use `this`) in typescript.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

https://stackoverflow.com/questions/43724426/this-is-undefined-inside-the-foreach-loop

**Comment by Yuyz0112** [comment]
@eoghanmurray The changes look good to me.

If I'm right, this patch is a 1-1 rewrite of the mutation processing code without any new logic and would be the base of the following changes.

Please let me know if I'm wrong. For example, if there are any logical changes to the processing flow and I would like to review that part again.

(I've already go through the patch, but Github's split view was not quite useful for comparing new files and deleted files)

**Comment by eoghanmurray** [comment]
Yes, this `mutationClass` branch is purely refactoring, and should not have any logical changes.  Apologies for delay.

**Comment by eoghanmurray** [comment]
#224 builds on top of this and has the logical changes discussed in #221 .

**Comment by Yuyz0112** [comment]
@eoghanmurray Thanks for the feedback, I would love to merge this patch and start to review the next one.

**Pull request merged**
