### PR TITLE
Add event async

### PR DESCRIPTION
**Pull request by eoghanmurray**
Enable addEvent to be used while there are still queued actions

 - addEvent was originally added to support 'live mode' (#73)
 - it was failing badly if used to add events before playback of current events has concluded, as assumption was that we were at end of playback
 - event wasn't getting added to list of events leading to incorrect totalTime metadata, and loss of added event upon replay from start
 - in a situation where events are being streamed to the replayer, this change supports asynchronous usage of addEvent (after you've added at least 2 initial events)

### CODE REVIEW

**Comment by eoghanmurray** [comment]
Oh yeah, previously if an addEvent was called too early, before the event that builds the DOM was completed, then an `Node id xxx is not found.` error was the result.  Have questioned @arun477 on #182 to see if that was the case with them.

**Comment by Yuyz0112** [comment]
#182 may also caused by the checkout feature.

Since the DOM observer Is async, we may capture some events after a full snapshot with invalid id.

**Comment by eoghanmurray** [comment]
Cool well you can disregard that reference to #182 .  I gues `Node id xx is not found` is a common generic error when things go wrong. I believe I was encountering because `addEvent` was happening before the first `FULLSNAPSHOT-REBUILDED` completed.

**Comment by Yuyz0112** [comment]
@eoghanmurray Would you like to rebase the master branch?

**Comment by eoghanmurray** [comment]
@Yuyz0112 yes have done so!

**Comment by Yuyz0112** [comment]
@eoghanmurray 

I have picked my work on the live mode to this PR: https://github.com/rrweb-io/rrweb/pull/226

Do you think I've solved the issues in this PR?

**Comment by eoghanmurray** [comment]
@Yuyz0112 #226 looks good; am I correct in saying it allows the option of turning off the buffering of mouse movements?

However 
> event wasn't getting added to list of events 
I don't see that being fixed in #226 ?
One goal of this pull request is to allow calls to `addEvent` to work correctly in terms of pushing the new event to the end of the queue.
As it currently stands, maybe `addEvent` should be renamed `playLiveEventNow`.

E.g. one goal of this PR is when events are being streamed _in_ to the player (even in a non-live context), you want to start playback asap, before you've downloaded all events.

**Comment by eoghanmurray** [comment]
As mentioned, the `addEvent` function in machine.ts now covers all this ground e.g. changes added in https://github.com/rrweb-io/rrweb/commit/8913bcb9d6bc50850474439b218b85a7e434d6a2

We're also now inserting in correct place after events are added with addEvent #411

So it's safe to close this one.

**Pull request closed without merging**
