### PR TITLE
Add support for StylesheetRule in document fragment

### LINKED ISSUE #285: seeking forward causing error
Hey, 

I'm getting error when I'm trying to seek forward the progress   

https://github.com/rrweb-io/rrweb/blob/be4cccd6e373c1a6702130a21a1d4557f2944101/src/replay/index.ts#L627

image

steps of reproducing the error:   
https://streamable.com/7df7v7   

rrweb version: 0.9 (latest)

Here is the repository that I'm working on that. https://github.com/raminious/rrweb-player   

`git clone git@github.com:raminious/rrweb-player.git`    
`npm install`   
`npm start`    
open `http://localhost:1234`

you can find the events array in `src/response.js`

### PR DESCRIPTION
**Pull request by Juice10**
Fix for one of the issues in #285. 

## Why this fix is needed
`styleEl.sheet` is not accessible when a `<style>` element is part of a FragmentDocument. This ends up triggering a: `Cannot read property 'rules' of null` error on the following line: https://github.com/rrweb-io/rrweb/blob/772c0e021a3e0fbbc60abee7ff47b0abc9fbd832/src/replay/index.ts#L676

### Additional information
I'm not 100% sure this is the most performant way to do this as moving the stylesheet element to and from the dom/fragment might have some performance implications.

But this fix does work and also includes tests in case someone would like to create a more performant fix for it later on.

_Edit: added some more information_

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Thanks, @Juice10 
I would like to merge this when the conflicts were resolved.

**Comment by Juice10** [comment]
@Yuyz0112 apologies for the long wait! Conflicts are resolved now, feel free to merge it in.

**Comment by Yuyz0112** [comment]
Thanks!

**Comment by Juice10** [comment]
@Yuyz0112 Thanks for the merge!

**Pull request merged**
