### PR TITLE
Enable external pausing of mutation buffer emissions

### PR DESCRIPTION
**Pull request by eoghanmurray**
- no automatic pausing based on e.g. pageVisibility yet, assuming such a thing is desirable
   https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
 - user code has to call new API method `freezePage` e.g. when page is hidden or after a timeout
 - automatically unpauses when the next user initiated event occurs
   (am assuming everything that isn't a mutation event counts as 'user initiated'
   either way think this is the correct thing to do until I see a counterexample
   of an event that shouldn't cause the mutations to be unbufferred)

### CODE REVIEW

**Comment by eoghanmurray** [comment]
410756e5fda39bf88b5bca791ef998a1752690f2 makes a change to delay processing of the \`addedSet\` until emission.  I'm not sure I understand this all, but the change solves an issue with a build up of additions (when the DOM was just cycling through nodes).

**Comment by eoghanmurray** [comment]
@Yuyz0112  I've rebased based on current master, would it be possible to get another review and merge if this change is okay?

This pull request adds a new API method `.freezePage` which allows mutations to be suspended externally.

We are using this to prevent pages which have e.g. a carousel implemented with DOM mutation from generating massive recordings even though the website visitor is not taking any actions (and might not even have the tab in focus)

**Comment by eoghanmurray** [comment]
Is `suspendMutations` a better name than `freezePage`?

**Comment by Yuyz0112** [comment]
For me, freezePage sounds more intuitive.

BTW, if I understand correctly, #385 contains all the changes in this PR and we can only review and discuss that one?

**Comment by eoghanmurray** [comment]
Yes, #385 is this pull request and more ... all further discussion can go there.

**Pull request closed without merging**
