### PR TITLE
fix(snapshot): dimensions for blocked element not being applied

### PR DESCRIPTION
**Pull request by billyvg**
Dimensions are not being properly applied when you seek to a position in the replay. Need to use `setProperty`, otherwise the style attributes get lost. This was happening when node was an RRElement.

### CODE REVIEW

**Comment by eoghanmurray** [comment]
Thank you for the contribution and for contributing tests :)

To further understand: this was a problem with RRDom but the original code was fine if applied in a real DOM context?

**Comment by billyvg** [comment]
@eoghanmurray correct, the test I added in `rebuild.test` works prior to this change.

**Review by YunFeng0817 — APPROVED** [review]
Thanks for the fix
Can you please add a change set log for this PR?

**Comment by eoghanmurray** [comment]
@billyvg this is good to merge, but could you either rebase/merge from master, or else tick the box to 'Allow edits from maintainers' so we can do that on your behalf?

**Pull request merged**
