### PR TITLE
Added mousemoveCallback threshold option to sampling config.

### PR DESCRIPTION
**Pull request by provinceinnovation**
(non-breaking) 
This PR lets you configure the throttle threshold for the mousemove callback. This enables you to adjust the frequency of mousemove events emission. Default remains at 500ms.

### CODE REVIEW

**Comment by Yuyz0112** [comment]
Thanks @provinceinnovation 

Could you tell me the use case of configuring this threshold?

**Comment by provinceinnovation** [comment]
This will allow us to configure the mouse movement second layer to transmit the mouse coordinate set more frequently than once every 500 ms. We are using this to so that we can provide a less laggy mouse movement playback in livemode with no playback 1000ms buffer.

(cc. https://github.com/rrweb-io/rrweb/blob/master/docs/observer.md#mouse-movement)

**Comment by galesky** [comment]
Thanks @provinceinnovation !

Could you also update `docs/observer.md` so that it includes this new parameter ?

I'd also suggest changing the name of the variable `threshold` to something like `mouseMoveThreshold`
and `callbackThreshold` to `mouseTransmitThreshold`

**Comment by Yuyz0112** [comment]
It's reasonable to me @provinceinnovation 

Thanks!

**Pull request merged**
