### PR TITLE
Add replayer.seek(timeOffset) to move the player to a moment in time

### PR DESCRIPTION
**Pull request by Juice10**
Builds on top of https://github.com/rrweb-io/rrweb/pull/264, please review that PR first.

Adds a `seek` method that pauses the player at a given time offset. It's similar to `replayer.play(2500); replayer.pause()` except that it won't trigger a race condition through `waitForStylesheetLoad` (https://github.com/rrweb-io/rrweb/issues/268).

## Example code
```javascript
const { Replayer } = rrweb;
const replayer = new Replayer(events);
replayer.seek(2500); //=> pauses the player at timeOffset 2500
```

Fixes https://github.com/rrweb-io/rrweb/issues/268

### CODE REVIEW

**Comment by Juice10** [comment]
Alternatively we could also call this method `pauseAt`

**Comment by Yuyz0112** [comment]
Hi @Juice10, could you take a look at this proposal? https://github.com/rrweb-io/rrweb/issues/274

**Comment by Yuyz0112** [comment]
Hi @Juice10, could you take a look at this proposal? https://github.com/rrweb-io/rrweb/issues/274

**Comment by Juice10** [comment]
Will do, thanks @Yuyz0112 !

**Comment by Yuyz0112** [comment]
https://github.com/rrweb-io/rrweb/issues/274 now provides a new pause API like this `pause(2500)`.

Please let me know if it does not fit your use case.

**Pull request closed without merging**
